# We're going to make a variable for RBpi version
# We want it to be compatible for pi3 & 4
RPI_VERSION ?= 4

# We also add a variable for the boot mount
# The boot
BOOTMNT ?= 

# initialize variable for cross-compiler

ARMGNU ?= aarch64-linux-gnu

